remote:
  real:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: covid19-short-term-forecasts-WP
      path: Shared Documents/orderly-real-outputs
  testing:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: covid19-short-term-forecasts-WP
      path: Shared Documents/orderly/orderly-testing-outputs

minimum_orderly_version: 1.1.32